name: crawler
run-name: crawler start to scrape cards data 🚀
on:
  push:
  schedule:
    - cron:  '2 * * * *'
jobs:
  scrape-cards-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run index.js
        run: npm start

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: 'data/*.csv'

          # Optional commit user and author settings
          commit_user_name: GitHub Actions Bot # defaults to "github-actions[bot]"
          commit_user_email: github-actions-bot@example.org # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run